name: Release

on:
  push:
    tags:
      - 'v*'

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.x
      uses: actions/setup-go@v5
      with:
        go-version: '1.22.2'

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: install garble
      run: go install mvdan.cc/garble@latest
    - name: Build
      run: |
        GOOS=windows GOARCH=amd64 garble -literals -tiny -seed=random build -o readtdose_win64.exe ./main.go

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        tag_name="${GITHUB_REF##*/}"
        gh release create "$tag_name" -t "$tag_name" readtdose*

